"""create models: user, request_ai, payment

Revision ID: 343a4416db27
Revises: 9f0bd4afccc8
Create Date: 2026-09-24 20:25:46.485114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343a4416db27'
down_revision: Union[str, Sequence[str], None] = '9f0bd4afccc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_column('payments', 'payment_url')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
